import { ESLint } from "eslint";

export default [
  {
    root: true,
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      ecmaFeatures: {
        jsx: true,
      },
    },
    env: {
      browser: true,
      commonjs: true,
      es6: true,
      node: true,
    },
    parser: "@typescript-eslint/parser",
    plugins: [
      "react",
      "prefer-arrow-functions",
      "eslint-plugin-prettier",
      "@typescript-eslint",
    ],
    extends: [
      "eslint:recommended",
      "plugin:react/recommended",
      "plugin:import/errors",
      "plugin:import/warnings",
      "plugin:jsx-a11y/recommended",
      "plugin:react-hooks/recommended",
      "airbnb",
      "eslint-config-prettier",
      "plugin:@next/next/recommended",
      "plugin:@typescript-eslint/recommended",
    ],
    rules: {
        "@typescript-eslint/no-explicit-any": "off", 
        "@typescript-eslint/no-unsafe-assignment": "off", 
        "@typescript-eslint/no-unsafe-call": "off",
      "react/react-in-jsx-scope": "off",
      "import/no-duplicates": "off",
      "import/no-unresolved": "off",
      "import/named": "off",
      "prettier/prettier": "off",
      "react/jsx-filename-extension": ["warn", { extensions: [".tsx"] }],
      "react/state-in-constructor": "off",
      "react/prop-types": "off",
      "react/no-access-state-in-setstate": "off",
      "react/no-danger": "off",
      "react/no-did-mount-set-state": "off",
      "react/no-did-update-set-state": "off",
      "react/no-will-update-set-state": "off",
      "react/no-redundant-should-component-update": "off",
      "react/no-this-in-sfc": "off",
      "react/no-typos": "off",
      "react/no-unused-state": "off",
      "react/jsx-no-bind": "off",
      "no-useless-call": "off",
      "no-useless-computed-key": "off",
      "no-useless-concat": "off",
      "no-useless-constructor": "off",
      "no-useless-rename": "off",
      "no-useless-return": "off",
      "react/jsx-props-no-spreading": "off",
      "react-hooks/exhaustive-deps": "off",
      "react/self-closing-comp": [
        "off",
        {
          component: true,
          html: true,
        },
      ],
      "no-constant-condition": ["off", { checkLoops: false }],
      "no-console": ["off", { allow: ["log", "warn", "off"] }],
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "no-underscore-dangle": "off",
      "prefer-arrow-functions/prefer-arrow-functions": [
        "warn",
        {
          classPropertiesAllowed: false,
          disallowPrototype: false,
          returnStyle: "unchanged",
          singleReturnOnly: false,
        },
      ],
      "react/function-component-definition": "off",
      "react/button-has-type": "off",
      "import/no-extraneous-dependencies": "off",
      "import/extensions": [
        "off",
        "ignorePackages",
        {
          ts: "never",
          tsx: "never",
        },
      ],
      "react/require-default-props": "off",
      "import/prefer-default-export": "off",
      "no-restricted-exports": "off",
      "react/no-unescaped-entities": "off",
      "no-shadow": "off",
      "@typescript-eslint/no-shadow": "off",
    },
    settings: {
      react: {
        version: "detect",
      },
      import/resolver: {
        typescript: {
          directory: "./tsconfig.json",
        },
        node: {
          extensions: [".js", ".jsx", ".ts", ".tsx"],
        },
      },
    },
  },
];
